server:
  port: 8030
spring:
  application:
    name: ribbon-hystrix-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    preferIpAddress: true