server:
  port: 8050
spring:
  application:
    name: config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Amsss/SpringCloud/    # 配置git仓库的地址
          search-paths: config-repo       # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: Amsss                                            # git仓库的账号
          password: lzsozmvzme123                                            # git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/