server:
  port: 8762
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer2
  client:
    registerWithEureka: true # 向注册中心注册自己 （默认为true）
    fetchRegistry: true # 检索服务列表 （默认为true）
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/